#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:0
#SBATCH --job-name=DATA
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=32000M
#SBATCH --array=1-10%10
#SBATCH --output=slurm/outputs/data/arrays/data_%A_%a.out

module purge
module load 2022
module load Miniconda3/4.12.0

source activate claficle

HPARAMS_FILE=slurm/data/process.array.txt

srun python -u claficle/data/benchmark.py \
  $(head -$SLURM_ARRAY_TASK_ID $HPARAMS_FILE | tail -1)
