#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=MEM
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=24:00:00
#SBATCH --mem=491520M
#SBATCH --output=slurm/outputs/tune/memory_%A.out

source "./slurm/.secrets"

module purge
module load 2022
module load Miniconda3/4.12.0

source activate claficle

srun python -u claficle/run/tune.py \
  data.sample_size_mb=1023 \
  model.causalLM_variant=distilgpt2
