stage: null # can be null, "debug" or "distillation"
post_init: False # whether to run model.post_init()
tokenizer_name: null

defaults:
  - run
  - _self_
  - override model: gewechselt/train
  - override data: oscar
  - override trainer: train
