# benchmark configuration for eval run
batch_size: 8 # desired effective batch size
k: 16 # number of examples shown
separator: "\n" # what to separate each example with
data_dir: "data/" # where to store the data
num_workers: 3 # num_workers for dataloaders
dataset_names: # list of huggingface dataset;split names
  # XGLUE
  - xglue;qam
  - xglue;nc

# to avoid hydra creating output dirs: https://stackoverflow.com/a/64635492/9889508
hydra:
  run:
    dir: .
  output_subdir: null
