# benchmark configuration for eval run
seed: 42 # will be overwritten by parent seed if run from parent script
batch_size: 5 # desired effective batch size
k: 16 # number of examples shown
separator: "\n" # what to separate each example with
data_dir: "data/" # where to store the data
num_workers: 16 # num_workers for dataloaders
extra_proc_fn: null # additional processing func, such as `translate`; override
dataset_names: # list of huggingface dataset;split names
  # XGLUE
  - xcsr;X-CODAH-en
  - xcsr;X-CSQA-en

# to avoid hydra creating output dirs: https://stackoverflow.com/a/64635492/9889508
hydra:
  run:
    dir: .
  output_subdir: null
