# benchmark configuration for eval run
seed: null # will be overwritten by parent seed if run from parent script
batch_size: 2 # desired effective batch size
k: 16 # number of examples shown
separator: "\n" # what to separate each example with
data_dir: "data/" # where to store the data
num_workers: 16 # num_workers for dataloaders
extra_proc_fn: null # additional processing func, such as `translate`; override
dataset_names: # list of huggingface dataset;split names
  # XGLUE
  - xglue;qam
  - xglue;qadsm
  - xglue;paws-x
  - xglue;xnli
  # CSQA
  - xcsr;X-CSQA-en
  - xcsr;X-CSQA-de
  - xcsr;X-CSQA-fr
  # CODAH
  - xcsr;X-CODAH-en
  - xcsr;X-CODAH-de
  - xcsr;X-CODAH-fr
  # multi eurlex - metaICL can't handle multi-label clssfctn
  # see https://github.com/facebookresearch/MetaICL/issues/15
  # - multi_eurlex;en
  # - multi_eurlex;de
  # - multi_eurlex;fr
  # hatecheck
  - Paul/hatecheck
  - Paul/hatecheck-german
  - Paul/hatecheck-french
  # amazon reviews
  - amazon_reviews_multi;en
  - amazon_reviews_multi;de
  - amazon_reviews_multi;fr
  # bigger datasets; xglue, wino_x, swiss_judgment
  - xglue;nc
  - demelin/wino_x;lm_en_de # english and german
  - demelin/wino_x;lm_en_fr # only french
  - swiss_judgment_prediction;mt_en
  - swiss_judgment_prediction;de
  - swiss_judgment_prediction;fr

# to avoid hydra creating output dirs: https://stackoverflow.com/a/64635492/9889508
hydra:
  run:
    dir: .
  output_subdir: null
